name: "Static Analysis"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    name: "Static Analysis"
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system: [ubuntu-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Tests"
        run: "vendor/bin/phpstan clear-result-cache -q && vendor/bin/phpstan"
